[profile.default]
solc-version = "0.8.21"

src = "src"
out = "out"
libs = ["lib"]
test = "test"
optimizer_runs = 10

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
